#%RAML 1.0 DataType
type: object
properties:
  _key:
    type: string
    description: key to retrieve an entity
    example: "123"
  created:
    description: RFC 3339 date
    type: string
  modified:
    description: RFC 3339 date
    type: string
  name:
    type: string
    example: "Parkour Club e.V."
  rechtsform:
    type: string
    example: "e.V."
  status:
    type: string
    example: "aktiv"
  mitgliedsstatus:
    type: string
    example: "mitglied"
  mitglieder:
    type: integer
    example: 100
  stimmen:
    type: integer
    example: 5
  beitrag:
    type: number
    example: 120.50
  ansprechpartner:
    type: string
    required: false
    example: "Max Mustermann"
  email:
    type: string
    required: false
    example: "info@parkour-club.de"
  adresse:
    type: string
    required: false
    example: "Musterstraße 1, 12345 Musterstadt"
  website_ok:
    type: boolean
    example: true
  parent_key:
    type: string
    required: false
    example: "456"
  owner_key:
    type: string
    example: "789"