#%RAML 1.0 DataType
type: object
properties:
  _key:
    type: string
    description: key to retrieve an entity
    example: "123"
  created:
    description: RFC 3339 date
    type: string
  modified:
    description: RFC 3339 date
    type: string
  name:
    type: string
    example: "Parkour Club e.V."
  rechtsform:
    type: string
    example: "e.V."
  membership:
    type: Membership
  mitglieder:
    type: integer
    example: 100
  stimmen:
    type: integer
    example: 5
  ansprechpartner:
    type: string
    required: false
    example: "Max Mustermann"
  email:
    type: string
    required: false
    example: "info@parkour-club.de"
  website_ok:
    type: boolean
    example: true
  website_pruefung:
    type: string
    description: RFC 3339 date
  parent_key:
    type: string
    required: false
    example: "456"
  owner_key:
    type: string
    example: "789"
  satzung_ok:
    type: boolean
    required: false
  satzung_pruefung:
    type: string
    description: RFC 3339 date
  register_ok:
    type: boolean
    required: false
  register_pruefung:
    type: string
    description: RFC 3339 date